// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PimUrbanGreen.Data;

#nullable disable

namespace PimUrbanGreen.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241123220302_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PimUrbanGreen.Models.PedidoWebModel", b =>
                {
                    b.Property<string>("Produto")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UsuarioPedido")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Usuario");

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Produto", "UsuarioPedido");

                    b.ToTable("PedidoWeb", (string)null);
                });

            modelBuilder.Entity("PimUrbanGreen.Models.ProdutoModel", b =>
                {
                    b.Property<string>("NomeProdutoAcabado")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantidadeEstoque")
                        .HasColumnType("int");

                    b.HasKey("NomeProdutoAcabado");

                    b.ToTable("ProdutoAcabado", (string)null);
                });

            modelBuilder.Entity("PimUrbanGreen.Models.UserModel", b =>
                {
                    b.Property<string>("NomeUsuario")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("NomeUsuario");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NomeUsuario");

                    b.ToTable("Usuarios", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
